# Generated by Django 4.2.7 on 2023-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
