# Generated by Django 4.2.7 on 2023-11-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
