# Generated by Django 4.2.7 on 2023-11-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards', '0003_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='box', to='study_with_cards.card_box'),
            preserve_default=False,
        ),
    ]
