# Generated by Django 4.2.7 on 2023-11-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards', '0004_deck_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='study_with_cards.deck'),
            preserve_default=False,
        ),
    ]
