# Generated by Django 4.2.7 on 2023-11-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards', '0004_alter_card_deck_alter_card_box_user_alter_deck_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
